### ISSUE TITLE
Errors when using namespaces

### ISSUE THREAD

**Issue by MARTIMM** [ufobat/p6-XML-XPath#10]
When I use namespaces and start a search on some element I get a lot of messages like **Use of uninitialized value $uri of type Any in string context.**
It happens in `XML::XPath::NodeTest` line 178 where `$uri` is tested for its namespace uri. The error is shown when a node is tested which does not have a namespace and the `$uri ` is still `Any`.
The line;
```
$take = $uri eq %*NAMESPACES{ $ns } && $node-name eq $name;
```
could be changed into
```
$take = ($uri//'') eq %*NAMESPACES{ $ns } && $node-name eq $name;
```
to get rid of the messages

Regards,
Marcel

**Comment by ufobat** [comment]
Thank you for the bug report. I am going to fix it tomorrow (hopefully), unless you want to send a PR yourself :-)
