### ISSUE TITLE
Fails tests when installing from zef

### ISSUE THREAD

**Issue by mikkelstb** [ufobat/p6-XML-XPath#13]
I am getting an error when running zef install XML::XPath
Using Rakudo Star version 2018.10 built on MoarVM version 2018.10 (v6.c)

```
===> Testing: XML::XPath:ver<0.9.3>
# Failed test 'XML trimmed string length is 3'
# at t/09_string_length_find.t line 37
# expected: '3'
#      got: '1'
# Looks like you failed 1 test of 13
===> Testing [FAIL]: XML::XPath:ver<0.9.3>
Aborting due to test failure: XML::XPath:ver<0.9.3> (use --force-test to override)
```

**Comment by ufobat** [comment]
That was the recent change I made to xml::xpath.

https://github.com/ufobat/p6-XML-XPath/commit/4a24be5d19ac663e20c1140123e42a111cc44f5b

It will go away when you update to the latest xml version. 

I will see if I can update the module dependencies of xml::xpath so it won't happen to others as well.

**Comment by mikkelstb** [comment]
I can confirm that by uninstalling and installing XML:ver<0.3.0> (previous 0.0.4), installing XML::XPath does so without errors.

**Comment by ufobat** [comment]
According to my research you need to have at least 0.1.0 of XML
